services:

  ml:
    build:
      context: .

    container_name: invoice-anomaly-detector

    volumes:
      - .:/app

    environment:
      PYTHONUNBUFFERED: "1"

    command: tail -f /dev/null

  postgres:
    image: postgres:18

    container_name: invoice-anomaly-postgres

    environment:

      POSTGRES_DB: anomaly_db

      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d anomaly_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
